eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    metadataMap.instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl.defaultZone: ${vcap.services.eureka-service.credentials.uri}/eureka/

#spring.zipkin.base-url=${vcap.services.zipkin-service.credentials.uri}
